const main = 'app';

const appClasses = {
  main,
  wrapper: `${main}__wrapper`,
  controls: `${main}__controls`,
  btn: {
    btn: `${main}__btn`,
    reloadBg: `${main}__btn--reloadBg`,
    speech: `${main}__btn--speech`,
    search: `${main}__btn--search`,
    fahrenheit: `${main}__btn--fahrenheit`,
    celsius: `${main}__btn--celsius`,
    temp: `${main}__btn--temp`,
    play: `${main}__btn--play`,
    close: `${main}__btn--close`,
    info: `${main}__btn--info`,
  },
  langs: `${main}__langs`,
  currLang: `${main}__langs-current-lang`,
  langsBtns: `${main}__lang-buttons`,
  search: `${main}__search`,
  searchInput: `${main}__search-input`,
  content: `${main}__content`,
  forecast: `${main}__forecast`,
  currInfo: `${main}__current-info`,
  geoInfo: `${main}__geo-info`,
  place: `${main}__place`,
  date: `${main}__date`,
  currForecast: `${main}__current-forecast`,
  currTemp: `${main}__current-temp`,
  currSummary: `${main}__current-summary`,
  currIcon: `${main}__current-weather-icon`,
  futForecast: `${main}__fut-forecast`,
  futItem: `${main}__future-item`,
  atlas: `${main}__atlas`,
  map: `${main}__map`,
  coords: `${main}__coords`,
  ticker: `${main}__ticker`,
  tickerWrapper: `${main}__ticker-wrapper`,
  popup: `${main}__popup`,
};

export { appClasses };
